// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW83xxh2O93V4buv8CDKTaUyBYiH05d0k',
    appId: '1:747783682746:web:76831ed0c8fc46c2d2a083',
    messagingSenderId: '747783682746',
    projectId: 'appli-histoire-aventure',
    authDomain: 'appli-histoire-aventure.firebaseapp.com',
    storageBucket: 'appli-histoire-aventure.firebasestorage.app',
    measurementId: 'G-FZX49744PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7GfGnHWA2D2fhsMx-Gt4Tg4ZkWoZBDs',
    appId: '1:747783682746:android:458b559e5ed54ef4d2a083',
    messagingSenderId: '747783682746',
    projectId: 'appli-histoire-aventure',
    storageBucket: 'appli-histoire-aventure.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqR7dGvxVS370psQH9m9U7CwyA7h8fVyo',
    appId: '1:747783682746:ios:2dcbceb0c584aeefd2a083',
    messagingSenderId: '747783682746',
    projectId: 'appli-histoire-aventure',
    storageBucket: 'appli-histoire-aventure.firebasestorage.app',
    iosBundleId: 'com.example.appliHistoireAventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqR7dGvxVS370psQH9m9U7CwyA7h8fVyo',
    appId: '1:747783682746:ios:2dcbceb0c584aeefd2a083',
    messagingSenderId: '747783682746',
    projectId: 'appli-histoire-aventure',
    storageBucket: 'appli-histoire-aventure.firebasestorage.app',
    iosBundleId: 'com.example.appliHistoireAventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW83xxh2O93V4buv8CDKTaUyBYiH05d0k',
    appId: '1:747783682746:web:86dd2e3dce70da01d2a083',
    messagingSenderId: '747783682746',
    projectId: 'appli-histoire-aventure',
    authDomain: 'appli-histoire-aventure.firebaseapp.com',
    storageBucket: 'appli-histoire-aventure.firebasestorage.app',
    measurementId: 'G-XSH2BK44JL',
  );
}
